bevacqua/dragula

readme.markdown
=> Fixed readme grammar error.

example/example.css
Layout is broken.
I changed the font size of the example code, to adapt in container.
=> Improves code examples layout.

example/example.css
=> Update transition to fix performance in Firefox

dragula.js, example/example.css
=> Update live demonstration with #78 performance fix

readme.markdown
Added obvious link to demo because UX. Quite a few people asking "where is the link?"
=> Added obvious link to demo because UX

index.html
Looks like a div got misplaced in copy-pasting.
=> minor documentation fix

dragula.js, readme.markdown
=> Over/Out Events

readme.markdown
=> Remove the scary graphic and link

readme.markdown
Initiated from discussion in https://github.com/bevacqua/dragula/issues/142
=> Added Troubleshooting section and CSS Classes subsection to readme

dragula.js
I assume it was reversed by mistake
=> _copy || _item reversed

example/example.css
=> handle container cursor

dragula.js, readme.markdown
PR for this issue [#187](https://github.com/bevacqua/dragula/issues/187)
=> Dropping also gives target element

dragula.js, readme.markdown
PR for [#211](https://github.com/bevacqua/dragula/issues/211)
@bevacqua please check
=> add source to emit event

dragula.js
=> fix input text selection issue #208

dragula.js
Tested on Android, iOS and current Firefox, Chrome and Edge.
See #239
=> Fixes touch functionality on mobile

dragula.js
See problem here: https://github.com/bevacqua/angular-dragula/issues/47
fixes bevacqua/angular-dragula#47
=> Small change allowing dragula.js to work inside iframe

dragula.js
I'm sorry for confusion, but I would like to tell you that with this pull request (https://github.com/bevacqua/dragula/commit/fe92c192df0c0e3525605cbc7e8ef84884211033) changes from this (https://github.com/bevacqua/dragula/commit/bc2536dd1ff6bc4bc0e930a2ca0724007f962b52) were lost.
Please merge this pull request to fix this issue again: https://github.com/bevacqua/dragula/issues/268#issuecomment-180505378
=> Can't repeatedly drop item" bug fixed

index.html
Example should be like source code https://github.com/bevacqua/dragula/blob/master/example/example.js#L29-L36 to work properly
Thanks
=> replace left with document.getElementById(left)

example/example.css, index.html
The preview can be found on https://cl.ly/ksLG
=> Install Carbon

example/example.css, index.html
I have a feeling this was bound to happen :p
* it's super secret.. but scroll down to the bottom of the page and move your mouse around! :D
=> Added a very important yet SUPER secret addition
